spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/reviewjhunter
    username: jhunter
    password: patrick
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        bus:
          enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
#actuator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  app:
    name: COMPANY SERVICE- JHUNTER application
    description: a spring boot MICROSERVICE application
    version: 1.0.0

logging:
  level:
    root: INFO
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/
server:
  port: 8083
